# Generated by Django 5.2.6 on 2025-09-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('status', models.CharField(choices=[('ready', 'Готово к работе'), ('progress', 'В работе'), ('done', 'Готово'), ('refused', 'Брак')], default='ready', max_length=20, verbose_name='Статус')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('operation_count', models.PositiveIntegerField(default=1, verbose_name='Кол-во операций')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за операцию')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
